"""Analyze whether two-parameter Born converges to UltraWave as contrast -> 0.

Requires RF generated by ``generate_ultrawave_contrast_continuation.py``.
For every sample and alpha it constructs the matching first-order c/rho Born
prediction and reports data-domain residual/coherence.  The key diagnostic is
whether the first-order model approaches the full-wave data in the weak-
contrast limit.

Expected first-order behavior if the source/measurement convention is right:

    alpha -> 0:
        coherence -> 1
        per-frequency-gain relative residual -> 0

A failure to improve even at alpha=0.05 points to a first-order source/Green
or measurement-convention mismatch rather than merely higher-order scattering.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F

PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT))

from common import rf_to_D  # noqa: E402
from physics.imaging import BornModel  # noqa: E402
from scripts.diagnose_two_parameter_born import (  # noqa: E402
    build_two_parameter_data,
    fit_summary,
    fit_two_term_per_frequency,
    rebuild_c_rho,
)
from scripts.pilot_phase_asp import DATA_ROOT, corrected_config, padded_meta  # noqa: E402

RHO0 = 1000.0


def alpha_tag(alpha: float) -> str:
    return f"alpha_{alpha:.3f}".replace(".", "p")


def load_continuation_rf(root: Path, sid: str, alpha: float):
    path = root / sid / f"{alpha_tag(alpha)}.npz"
    if not path.exists():
        raise FileNotFoundError(
            f"missing {path}; run generate_ultrawave_contrast_continuation.py first")
    with np.load(path) as f:
        rf = np.asarray(f["rf"], dtype=np.float32)
        md = json.loads(str(f["metadata_json"].item()))
    if rf.shape != (11, 192, 2401):
        raise RuntimeError(f"unexpected RF shape {rf.shape} in {path}")
    if abs(float(md["contrast_alpha"]) - alpha) > 1e-9:
        raise RuntimeError(f"alpha metadata mismatch in {path}")
    if md.get("attenuation_mode") != "uniform_reference":
        raise RuntimeError("continuation RF must use homogeneous attenuation")
    return rf, md


def scale_medium(c: torch.Tensor, rho: torch.Tensor, alpha: float, c0: float):
    ca = c0 + alpha * (c - c0)
    ra = RHO0 + alpha * (rho - RHO0)
    return ca, ra


def compact_fit(summary: dict):
    return {
        "residual": summary["per_frequency_relative_residual"],
        "frequency_coherence": summary["mean_frequency_coherence"],
        "angle_coherence": summary["mean_angle_coherence"],
        "element_coherence": summary["mean_element_coherence"],
    }


def plot_sample(path: Path, sid: str, rows: list[dict], dpi: int):
    alphas = np.asarray([r["alpha"] for r in rows])
    names = ["c_only", "rho_only", "c_plus_rho", "two_term_oracle"]

    fig, axes = plt.subplots(2, 2, figsize=(10.5, 8.0), constrained_layout=True)
    metrics = [
        ("frequency_coherence", "Mean frequency coherence", (0, 1.02)),
        ("angle_coherence", "Mean angle coherence", (0, 1.02)),
        ("element_coherence", "Mean element coherence", (0, 1.02)),
        ("residual", "Per-frequency-gain relative residual", (0, 1.05)),
    ]
    for ax, (key, title, ylim) in zip(axes.ravel(), metrics):
        for name in names:
            ax.plot(alphas, [r["fit"][name][key] for r in rows], marker="o", label=name)
        ax.set_xlabel("Contrast scale alpha")
        ax.set_ylabel(key)
        ax.set_title(title)
        ax.set_ylim(*ylim)
        ax.grid(alpha=0.25)
    axes[0, 0].legend(fontsize=8)
    fig.suptitle(f"{sid}: weak-contrast convergence diagnostic")
    fig.savefig(path, dpi=dpi)
    plt.close(fig)


def weak_limit_diagnosis(rows: list[dict]):
    rows = sorted(rows, key=lambda r: r["alpha"])
    weak = rows[0]
    full = rows[-1]
    fixed_weak = weak["fit"]["c_plus_rho"]
    fixed_full = full["fit"]["c_plus_rho"]
    oracle_weak = weak["fit"]["two_term_oracle"]
    return {
        "weakest_alpha": weak["alpha"],
        "full_alpha": full["alpha"],
        "fixed_sum_frequency_coherence_weak": fixed_weak["frequency_coherence"],
        "fixed_sum_frequency_coherence_full": fixed_full["frequency_coherence"],
        "fixed_sum_residual_weak": fixed_weak["residual"],
        "fixed_sum_residual_full": fixed_full["residual"],
        "two_term_oracle_frequency_coherence_weak": oracle_weak["frequency_coherence"],
        "two_term_oracle_residual_weak": oracle_weak["residual"],
        "weak_minus_full_frequency_coherence": (
            fixed_weak["frequency_coherence"] - fixed_full["frequency_coherence"]),
        "full_minus_weak_residual": fixed_full["residual"] - fixed_weak["residual"],
    }


@torch.no_grad()
def analyze_sample(sid: str, alphas: list[float], continuation_root: Path,
                   args, device):
    sample = torch.load(DATA_ROOT / "shards" / f"{sid}.pt",
                        map_location="cpu", weights_only=False)
    cfg, meta = corrected_config(args.config, sample, args.imaging_n_freq)
    if len(meta.band_idx) > 1 and not np.all(np.diff(meta.band_idx) == 1):
        raise RuntimeError("analysis requires contiguous full-band frequencies")

    c_np, rho_np, max_c_err = rebuild_c_rho(sample, cfg.physics.c0)
    c = torch.from_numpy(c_np).to(device)[None]
    rho = torch.from_numpy(rho_np).to(device)[None]

    pmeta = padded_meta(meta, args.pad, cfg.grid.dx)
    born = BornModel(
        pmeta,
        cfg.grid.nx + 2 * args.pad,
        cfg.grid.nz,
        cfg.grid.dx,
        cfg.grid.dz,
        cfg.physics.c0,
        eps=cfg.physics.eps_evanescent,
        spreading=cfg.physics.spreading,
    ).to(device)
    zero = torch.zeros(1, cfg.grid.nz, cfg.grid.nx + 2 * args.pad,
                       device=device, dtype=torch.float32)
    all_idx = torch.arange(len(meta.angles_deg), device=device)
    u0 = born.transmit_fields(zero, all_idx)

    rows = []
    for alpha in alphas:
        rf_np, raw_md = load_continuation_rf(continuation_root, sid, alpha)
        Duw = rf_to_D(torch.from_numpy(rf_np)[None].to(device), meta)

        ca, ra = scale_medium(c, rho, alpha, cfg.physics.c0)
        ca_pad = F.pad(ca, (args.pad, args.pad), value=float(cfg.physics.c0))
        # Deliberately use the true homogeneous reference density at the lateral pad.
        ra_pad = F.pad(ra, (args.pad, args.pad), value=RHO0)
        Dc, Dr = build_two_parameter_data(
            born, ca_pad, ra_pad, u0, zero, cfg.physics.c0)
        Dsum = Dc + Dr
        Doracle, _ = fit_two_term_per_frequency(Dc, Dr, Duw)

        models = {
            "c_only": Dc,
            "rho_only": Dr,
            "c_plus_rho": Dsum,
            "two_term_oracle": Doracle,
        }
        fits = {}
        for name, pred in models.items():
            summary, _, _, _ = fit_summary(pred, Duw)
            fits[name] = compact_fit(summary)

        rows.append({
            "alpha": float(alpha),
            "rf_rms": float(np.sqrt(np.mean(rf_np.astype(np.float64) ** 2))),
            "fit": fits,
            "raw_metadata": {
                "attenuation_mode": raw_md["attenuation_mode"],
                "raw_scattered_rf_rms": raw_md["raw_scattered_rf_rms"],
            },
        })
        print(json.dumps({
            "event": "alpha_analyzed",
            "sample": sid,
            "alpha": alpha,
            "fixed": fits["c_plus_rho"],
            "oracle": fits["two_term_oracle"],
        }), flush=True)

    rows.sort(key=lambda r: r["alpha"])
    plot_sample(args.out / f"{sid}_contrast_convergence.png", sid, rows, args.dpi)
    return {
        "sample": sid,
        "case": sample["metadata"].get("case"),
        "reconstruction_check": {
            "max_abs_c_error_m_per_s": max_c_err,
            "rho_padding_reference_kg_per_m3": RHO0,
        },
        "rows": rows,
        "weak_limit": weak_limit_diagnosis(rows),
    }


def aggregate(samples: list[dict]):
    alphas = sorted({r["alpha"] for s in samples for r in s["rows"]})
    out = {}
    for alpha in alphas:
        selected = [r for s in samples for r in s["rows"]
                    if abs(r["alpha"] - alpha) < 1e-12]
        per_model = {}
        for name in ("c_only", "rho_only", "c_plus_rho", "two_term_oracle"):
            per_model[name] = {
                key: float(np.mean([r["fit"][name][key] for r in selected]))
                for key in ("residual", "frequency_coherence",
                            "angle_coherence", "element_coherence")
            }
        out[str(alpha)] = per_model
    return out


def plot_aggregate(path: Path, aggregate_rows: dict, dpi: int):
    alphas = np.asarray(sorted(float(a) for a in aggregate_rows))
    names = ["c_plus_rho", "two_term_oracle"]
    fig, axes = plt.subplots(1, 2, figsize=(9.5, 4.0), constrained_layout=True)
    for name in names:
        axes[0].plot(
            alphas,
            [aggregate_rows[str(float(a))][name]["frequency_coherence"] for a in alphas],
            marker="o", label=name)
        axes[1].plot(
            alphas,
            [aggregate_rows[str(float(a))][name]["residual"] for a in alphas],
            marker="o", label=name)
    axes[0].set(xlabel="Contrast scale alpha", ylabel="Mean frequency coherence",
                title="Weak-limit coherence", ylim=(0, 1.02))
    axes[1].set(xlabel="Contrast scale alpha", ylabel="Relative residual",
                title="Weak-limit residual", ylim=(0, 1.05))
    for ax in axes:
        ax.grid(alpha=0.25)
        ax.legend()
    fig.savefig(path, dpi=dpi)
    plt.close(fig)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--config", default="configs/l11_ultrawave_500_11angle.yaml")
    p.add_argument("--continuation-root", type=Path, default=None)
    p.add_argument("--sample-ids", nargs="+", default=["val_000"])
    p.add_argument("--alphas", nargs="+", type=float,
                   default=[0.05, 0.1, 0.25, 0.5, 1.0])
    p.add_argument("--gpu", type=int, default=0)
    p.add_argument("--pad", type=int, default=32)
    p.add_argument("--imaging-n-freq", type=int, default=0)
    p.add_argument("--dpi", type=int, default=160)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()

    alphas = sorted(set(float(a) for a in args.alphas))
    if not alphas or any(a <= 0 or a > 1 for a in alphas):
        p.error("all --alphas must lie in (0, 1]")
    continuation_root = args.continuation_root or (DATA_ROOT / "contrast_continuation")
    args.out.mkdir(parents=True, exist_ok=True)

    torch.cuda.set_device(args.gpu)
    device = torch.device(f"cuda:{args.gpu}")
    samples = [
        analyze_sample(sid, alphas, continuation_root, args, device)
        for sid in args.sample_ids
    ]
    agg = aggregate(samples)
    plot_aggregate(args.out / "contrast_convergence_aggregate.png", agg, args.dpi)

    payload = {
        "samples": args.sample_ids,
        "alphas": alphas,
        "continuation_root": str(continuation_root),
        "rho_padding_reference_kg_per_m3": RHO0,
        "aggregate": agg,
        "sample_results": samples,
    }
    (args.out / "contrast_continuation_diagnostic.json").write_text(
        json.dumps(payload, indent=2) + "\n")
    print(json.dumps({"event": "done", "aggregate": agg}), flush=True)


if __name__ == "__main__":
    main()
